### ISSUE TITLE
Clear cache

### ISSUE THREAD

**Issue by dutchiexl** [netresearch/composer-patches-plugin#10]
I added a patch with a wrong url, and I updated the url, but it is never updated when updateing composer.
<code>
"drupal/drupal": {
              "7.35": [
                {
                  "title": "Fixes the ckeditor version not found 1 problem.",
                  "url": "./patches/locale_throwing_notice_1.patch"
                }
              ]
            }
</code>

**Comment by copitz** [comment]
Have you considered clearing the [composer cache](https://getcomposer.org/doc/03-cli.md#clear-cache)?

**Comment by dutchiexl** [comment]
Yes, I did that multiple times, but it did not work.

**Comment by mathieuhelie** [comment]
We had a similar issue with a patch we added to our composer.json, which actually was the second patch added to the project. It would not be added to composer.lock no matter what we tried.

It turned out that we had to delete netresearch/composer-patches-plugin from our vendor directory, and only then would composer install apply all the patches and write them to the composer.lock.

**Comment by mathieuhelie** [comment]
More details for you - we found out that if the contrib module we want to patch has already been patched in composer's cache, composer-patches-plugin will attempt to apply the patch on top, thus causing the patch command to *revert* the patch, or failing entirely in some cases.

**Comment by copitz** [comment]
Thank you for the infos - we'll probably have to rethink the way, the applied patches are determined. I'll have a look at this asap

**Comment by mathieuhelie** [comment]
We ended up resolving most of our problems when we found https://github.com/netresearch/composer-patches-plugin/issues/6#issuecomment-73097154

The problem was that the behavior was not documented in the Readme, and maybe our team is not familiar enough with composer to guess at it. Simply patching the Readme should do the trick.

**Comment by copitz** [comment]
With 1.2.0 the patching process was overworked - thus I don't see a todo for now. Thanks for your feedback!
